### PR TITLE
Add total points number to attendance_committee show route.

### LINKED ISSUE #38: Display Points/Attendance logs for specific comittee on Comittee Attendance

### PR DESCRIPTION
**Pull request by cdconn00**
Closes #38

### CODE REVIEW

**Comment by Buzzec** [comment]
Use dev as your base branch, this currently has a lot of conflicts

**Comment by cdconn00** [comment]
I think I did, but the changes hadn't been pulled in yet. Should I just make a new branch and copy the code over?

**Comment by cdconn00** [comment]
Actually, this is pretty simple, I can make the merge if that's cool

**Comment by Buzzec** [comment]
You should merge dev into yours first

**Comment by cdconn00** [comment]
@Buzzec ready for review

**Review by Buzzec — CHANGES_REQUESTED** [review]
Instead of just total points put the same row you display for index at the top of show

**Comment by cdconn00** [comment]
@Buzzec ready for re-review.

**Review by Buzzec — APPROVED** [review]

**Pull request merged**
